default_language_version:
  python: '3.12'

repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v5.0.0
    hooks:
      - id: check-added-large-files
        args: [--maxkb=8192]
      - id: check-ast
      - id: check-case-conflict
      - id: check-merge-conflict
      - id: check-toml
      - id: check-yaml
      - id: debug-statements
      - id: detect-private-key
      - id: double-quote-string-fixer
      - id: end-of-file-fixer
      - id: fix-byte-order-marker
      - id: requirements-txt-fixer
      - id: trailing-whitespace
      - id: mixed-line-ending
        args: [--fix=auto]

  - repo: https://github.com/charliermarsh/ruff-pre-commit
    rev: v0.9.6
    hooks:
      - id: ruff
        exclude: development/copied/unmodified/
        types_or: [python, pyi]
        args: [--fix]

      - id: ruff-format
        exclude: development/copied/unmodified/
        types_or: [python, pyi]

  - repo: https://github.com/codespell-project/codespell
    rev: v2.4.1
    hooks:
      - id: codespell
        exclude: development/copied/unmodified/

  - repo: https://github.com/lorenzwalthert/gitignore-tidy
    rev: 0.1.2
    hooks:
      - id: tidy-gitignore

  - repo: https://github.com/Yelp/detect-secrets
    rev: v1.5.0
    hooks:
      - id: detect-secrets
        exclude: dist|target|public|.*\.lock\..*|.*example.*|.*\.agebox

  - repo: https://github.com/pre-commit/mirrors-prettier
    rev: v4.0.0-alpha.8
    hooks:
      - id: prettier
        exclude: development/copied/unmodified/|dist|target|public|.*\.lock\..*|.*example.*
        types_or:
          - javascript
          - json
          - jsx
          - svg
          - ts
          - tsx
          - yaml
          - css
          - mdx

  - repo: https://github.com/commitizen-tools/commitizen
    rev: v4.2.1
    hooks:
      - id: commitizen
      - id: commitizen-branch
        stages: [manual]

  - repo: https://github.com/ComPWA/taplo-pre-commit
    rev: v0.9.3
    hooks:
      - id: taplo-format
      - id: taplo-lint
